"""change name for model PrivatE Settings

Revision ID: 34c8560bce73
Revises: bb31acac5dd6
Create Date: 2019-11-10 12:24:22.512474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c8560bce73'
down_revision = 'bb31acac5dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('secret_key', sa.String(length=128), nullable=True),
    sa.Column('public_key', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('privat_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privat_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('exchange_id', sa.INTEGER(), nullable=True),
    sa.Column('secret_key', sa.VARCHAR(length=128), nullable=True),
    sa.Column('public_key', sa.VARCHAR(length=128), nullable=True),
    sa.Column('name', sa.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('private_settings')
    # ### end Alembic commands ###
