"""test1

Revision ID: bcf0ff1fa65e
Revises: d6922c8b848c
Create Date: 2019-10-08 10:09:34.007206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf0ff1fa65e'
down_revision = 'd6922c8b848c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privat_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('secret_key', sa.String(length=128), nullable=True),
    sa.Column('public_key', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_exchanges')
    op.create_index(op.f('ix_exchange_name'), 'exchange', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_name'), table_name='exchange')
    op.create_table('users_exchanges',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('exchange_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('privat_settings')
    # ### end Alembic commands ###
